### ISSUE TITLE
私聊发送文件时出现 Error: 未知文件类型 报错

### ISSUE THREAD

**Issue by Jackxwb** [LLOneBot/llonebot.nix#10]
Docker部署，映射`AstrBot`的数据文件到容器内部

请求接口`/upload_private_file`，[参考文档](https://docs.go-cqhttp.org/api/#%E4%B8%8A%E4%BC%A0%E7%A7%81%E8%81%8A%E6%96%87%E4%BB%B6))
请求内容
```
{
  "user_id": {{myQQ}},
  "file": "/AstrBot/data/plugins/ ... 文件打码 ... /00001.jpg",
  "name": "00001.jpg"
}
```
接口返回内容
```
{
  "status": "failed",
  "retcode": 200,
  "data": null,
  "message": "Error: 未知文件类型",
  "wording": "Error: 未知文件类型"
}
```
文件权限已设为777，更换成PDF文件也报错这个错。

![Image](https://github.com/user-attachments/assets/30f4c03d-147e-4664-a36f-a3215c5a29b4)

compose.yaml 配置如下
```
version: "3.3"
services:
  llonebot:
    container_name: llonebot_qqbot
    restart: unless-stopped
    #network_mode: bridge
    network_mode: host
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:7081
    environment:
      - VNC_PASSWD=${pass}
    volumes:
      #  - ${mainPath}/root:/root
      - ${mainPath}/database:/LiteLoader/data/LLOneBot/database
      - ${mainPath}/logs:/LiteLoader/data/LLOneBot/logs
      - ${mainPath}/QQ:/data/.config/QQ
      - ${AstrBot}/data/plugins:/AstrBot/data/plugins
    privileged: true
    image: initialencounter/llonebot:latest
networks: {}
```

**Comment by linyuchen** [comment]
提供一下llonebot的日志，在${mainPath}/logs里面

**Comment by Jackxwb** [comment]
> 提供一下llonebot的日志，在${mainPath}/logs里面

```
4/5/2025, 6:53:46 AM [info] (1687862774) | onebot WebSocket 事件上报 ws://127.0.0.1:2021/ws meta_event

4/5/2025, 6:54:24 AM [info] (1687862774) | onebot 收到 HTTP 请求 /upload_private_file { user_id: 1142263811, file: '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/1115459.pdf', name: '1115459.pdf' }

4/5/2025, 6:54:25 AM [error] (1687862774) | onebot 发生错误 Error: 未知文件类型 at UploadPrivateFile._handle (/LiteLoader/plugins/LLOneBot/main/main.cjs:353:165717) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async UploadPrivateFile.handle (/LiteLoader/plugins/LLOneBot/main/main.cjs:353:51144) at async OB11Http.handleRequest (/LiteLoader/plugins/LLOneBot/main/main.cjs:353:49032)

```

**Comment by Jackxwb** [comment]
试了下，好像把文件、图片转换成base64数据发送的话，能正常发送，但使用路径的话，就会报这个错。
---
参考[这个页面](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)的提示，在文件路径前面加入`file://`，会提示：`Error: ENOENT: no such file or directory, open '/AstrBot/...省略.../pdf/test.jpg'`
日志信息：
```
4/5/2025, 9:21:02 AM [info] (1687862774) | onebot 收到 HTTP 请求 /send_private_msg { user_id: '匿QQ号', message: [ { type: 'image', data: { file: 'file:///AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg' } } ] }

4/5/2025, 9:21:02 AM [error] (1687862774) | onebot 发生错误 [Error: ENOENT: no such file or directory, open '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg' }

```
是不是我Docker路径映射的有问题？
```
# docker exec -it llonebot_qqbot /bin/bash
bash-5.2# cd /AstrBot/data/plugins/FateTrial_jmdownloader/pdf/
bash-5.2# ls -l
total 16092
-rwxrwxrwx 1 0 0 15267080 Apr  3 10:01 1115459.pdf
-rwxrwxrwx 1 0 0  1005677 Apr  5 09:09 test.jpg
-rwxrwxrwx 1 0 0   195887 Apr  5 07:09 test.pdf
```

**Comment by linyuchen** [comment]
> 试了下，好像把文件、图片转换成base64数据发送的话，能正常发送，但使用路径的话，就会报这个错。
> 
> ---
> 
> 参考[这个页面](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)的提示，在文件路径前面加入`file://`，会提示：`Error: ENOENT: no such file or directory, open '/AstrBot/...省略.../pdf/test.jpg'`
> 日志信息：
> ```
> 4/5/2025, 9:21:02 AM [info] (1687862774) | onebot 收到 HTTP 请求 /send_private_msg { user_id: '匿QQ号', message: [ { type: 'image', data: { file: 'file:///AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg' } } ] }
> 
> 4/5/2025, 9:21:02 AM [error] (1687862774) | onebot 发生错误 [Error: ENOENT: no such file or directory, open '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg' }
> 
> ```
> 是不是我Docker路径映射的有问题？
> ```
> # docker exec -it llonebot_qqbot /bin/bash
> bash-5.2# cd /AstrBot/data/plugins/FateTrial_jmdownloader/pdf/
> bash-5.2# ls -l
> total 16092
> -rwxrwxrwx 1 0 0 15267080 Apr  3 10:01 1115459.pdf
> -rwxrwxrwx 1 0 0  1005677 Apr  5 09:09 test.jpg
> -rwxrwxrwx 1 0 0   195887 Apr  5 07:09 test.pdf
> ```
> 

看报错是路径问题

**Comment by Jackxwb** [comment]
> > 试了下，好像把文件、图片转换成base64数据发送的话，能正常发送，但使用路径的话，就会报这个错。
> > 
> > 参考[这个页面](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)的提示，在文件路径前面加入`file://`，会提示：`Error: ENOENT: no such file or directory, open '/AstrBot/...省略.../pdf/test.jpg'`
> > 日志信息：
> > ```
> > 4/5/2025, 9:21:02 AM [info] (1687862774) | onebot 收到 HTTP 请求 /send_private_msg { user_id: '匿QQ号', message: [ { type: 'image', data: { file: 'file:///AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg' } } ] }
> > 
> > 4/5/2025, 9:21:02 AM [error] (1687862774) | onebot 发生错误 [Error: ENOENT: no such file or directory, open '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/AstrBot/data/plugins/FateTrial_jmdownloader/pdf/test.jpg' }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是不是我Docker路径映射的有问题？
> > ```
> > # docker exec -it llonebot_qqbot /bin/bash
> > bash-5.2# cd /AstrBot/data/plugins/FateTrial_jmdownloader/pdf/
> > bash-5.2# ls -l
> > total 16092
> > -rwxrwxrwx 1 0 0 15267080 Apr  3 10:01 1115459.pdf
> > -rwxrwxrwx 1 0 0  1005677 Apr  5 09:09 test.jpg
> > -rwxrwxrwx 1 0 0   195887 Apr  5 07:09 test.pdf
> > ```
> 
> 看报错是路径问题

通过VNC连接到QQ界面，使用QQ自动的发送文件触发的文件浏览器里的路径好像和Docker容器的里的路径不一样，是不是需要额外的配置，才能将文件映射到QQ的虚拟环境里？

**Comment by linyuchen** [comment]
不需要额外配置的，传入的路径只要是docker中的绝对路径就可以，LLOneBot没有识别到估计就是映射有问题

**Comment by Jackxwb** [comment]
> 不需要额外配置的，传入的路径只要是docker中的绝对路径就可以，LLOneBot没有识别到估计就是映射有问题

好像映射到根目录下不会被识别到。

![Image](https://github.com/user-attachments/assets/6c4d55b3-22fb-48ba-a906-9a8836475bb9)

映射到 `/LiteLoader` 目录下，就可以见到。

![Image](https://github.com/user-attachments/assets/d97aa202-01be-4425-887c-3bdd5d5ddf62)

我记得最开始登录二维码会保存到QQ环境的/root文件夹下面，我尝试过，也没有映射出来。


---

刚刚试了下，将`testPath`映射到：根目录、/roo目录、/usr目录、/LiteLoader目录下，但在QQ环境下，只有 /LiteLoader目录 下出现testPath这个目录

![Image](https://github.com/user-attachments/assets/f56cc448-ba40-42ad-a311-6f84b08a99ab)

---

另外，好像重建容器后`llonebot`的配置会丢失（反代ws的配置不见了），想问下，llonebot的配置是保存在哪里的？

![Image](https://github.com/user-attachments/assets/a96af181-395e-4b02-aade-d3e940e01147)

附上现在的Docker compose
```
version: "3.3"
services:
  llonebot:
    container_name: llonebot_qqbot
    restart: unless-stopped
    #network_mode: bridge
    network_mode: host
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:7081
    environment:
      - VNC_PASSWD=${pass}
    volumes:
      #  - ${mainPath}/root:/root
      - ${mainPath}/database:/LiteLoader/data/LLOneBot/database
      - ${mainPath}/logs:/LiteLoader/data/LLOneBot/logs
      - ${mainPath}/QQ:/data/.config/QQ
      - ${AstrBot}/data/plugins:/LiteLoader/AstrBot/data/plugins
      - ${mainPath}/testPath:/testPath
      - ${mainPath}/testPath:/root/testPath
      - ${mainPath}/testPath:/usr/testPath
      - ${mainPath}/testPath:/LiteLoader/testPath
    privileged: true
    image: initialencounter/llonebot:latest
networks: {}
```
