### ISSUE TITLE
ws反代没生效

### ISSUE THREAD

**Issue by iTofu** [LLOneBot/llonebot.nix#14]
docker-compose.yml:

```yml
services:
  gsuidcore:
    image: lilixxs666/gsuid-core:dev
    container_name: gsuidcore
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GSCORE_HOST=${GSCORE_HOST}
    ports:
      - "8765:8765"
    volumes:
      - ./gscore_data:/gsuid_core/data
      - ./gscore_plugins:/gsuid_core/gsuid_core/plugins
    networks:
      - koishi_network

  # napcat:
  #   image: mlikiowa/napcat-docker:latest
  #   # image: mlikiowa/napcat-docker:v4.7.33
  #   container_name: napcat
  #   restart: unless-stopped
  #   environment:
  #     - NAPCAT_UID=${NAPCAT_UID}
  #     - NAPCAT_GID=${NAPCAT_GID}
  #     - MODE=${MODE}
  #     - WEBUI_TOKEN=${WEBUI_TOKEN}
  #     - ACCOUNT=${ACCOUNT}
  #   ports:
  #     - "6099:6099"
  #   volumes:
  #     - ./napcat:/app/napcat
  #     - ./ntqq:/app/.config/QQ
  #     - ./koishi:/koishi
  #   networks:
  #     - koishi_network
  #   mac_address: "02:42:ac:11:00:02"

  llonebot:
    image: initialencounter/llonebot:latest
    container_name: llonebot
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - VNC_PASSWD=${VNC_PASSWD}
    ports:
      - "3081:3000" # 主机 3000 端口被占用
      - "7081:7081"
    privileged: true
    networks:
      - koishi_network

  koishi:
    image: koishijs/koishi:latest
    container_name: koishi
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "5140:5140"
    volumes:
      # - ./napcat:/app/napcat
      # - ./ntqq:/app/.config/QQ
      - ./koishi:/koishi
    networks:
      - koishi_network

networks:
  koishi_network:
    driver: bridge
```

跑在 Mac mini M4 上，docker 镜像是刚 pull 的 latest。

LLOneBot 配置，尝试了三种 host（之前在 NapCat 时是使用 `ws://koshi:5140/onebot` 正常连通）：

<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/ff82b1c0-13b5-40a3-90d7-d80fc60888b0" />

有三个问题哈：

1. 在 VNC 里配置 ws 反代后，测试发送消息发现没反应。
2. 登录后，log 发现还在疯狂 log "登录二维码推送中..."。`docker compose logs -f llonebot`:
    ```bash
    ...
    llonebot  | 11/05/2025 10:32:22 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000456)
    llonebot  | 11/05/2025 10:32:22 Switching from zlib to zlib Encoding for client 192.168.158.1
    llonebot  | 10:32:26.249 › [196bee6e856][hot update] ------------ app 启动分界线 ------------
    llonebot  | 10:32:26.264 › [196bee6e856][hot update] hotUpdateApi checkHasMultipleQQ:  false
    llonebot  | 10:32:26.265 › [196bee6e856][hot update] hotUpdateApi clearOldVersions start
    llonebot  | 10:32:26.269 › [196bee6e856][hot update] {
    llonebot  |   "baseVersion": "3.2.16-33800",
    llonebot  |   "curVersion": "3.2.16-33800",
    llonebot  |   "prevVersion": "",
    llonebot  |   "onErrorVersions": [],
    llonebot  |   "buildId": "33800",
    llonebot  |   "unzipRetryCount": 0
    llonebot  | }
    llonebot  | 10:32:26.301 › [196bee6e856][hot update] ----- startUpdate -----
    llonebot  | 10:32:26.307 › [196bee6e856][hot update] hotUpdateApi checkHasMultipleQQ:  false
    llonebot  | 10:32:26.308 › [196bee6e856][hot update] hotUpdateApi start check  3.2.17-34362  IsOnErrorVersion
    llonebot  | 10:32:26.308 › [196bee6e856][hot update] hotUpdateApi checkIsOnErrorVersion result: false
    llonebot  | 10:32:26.309 › [196bee6e856][hot update] [startUpdate] is fullUpdate: true
    llonebot  | 10:32:26.379 › [196bee6e856][hot update] hotUpdateApi cancel
    llonebot  | 10:32:26.380 › [196bee6e856][hot update] onStatusChanged status:  IDLE
    llonebot  | 10:32:26.380 › [196bee6e856][hot update] onUpdateCancel
    llonebot  | 11/05/2025 10:32:26 client 2 network rate 4198.5 KB/sec (230979.5 eff KB/sec)
    llonebot  | 11/05/2025 10:32:26 client 2 latency:  0.5 ms
    llonebot  | 11/05/2025 10:32:26 dt1: 0.0102, dt2: 0.0017 dt3: 0.0005 bytes: 50181
    llonebot  | 11/05/2025 10:32:26 link_rate: LR_LAN - 1 ms, 4198 KB/s
    llonebot  | [2025-05-11 10:32:27] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:30] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
    llonebot  | [NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/root/.config/QQ/crash_files/rqd_record.eup.
    llonebot  | [NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
    llonebot  | api call returning 0
    llonebot  | [2025-05-11 10:32:32] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:35] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:37] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:40] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:41] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:42] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:45] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:46] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:47] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:50] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:51] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:52] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:55] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:56] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:32:57] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:00] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:01] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:02] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:05] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:06] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:07] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:10] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:11] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:12] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:16] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [37:0511/103317.216680:ERROR:browser_main_loop.cc(278)] GLib-GObject: ../gobject/gsignal.c:2685: instance '0x2ab800102440' has no handler with id '1574'
    llonebot  | [2025-05-11 10:33:17] [LoginAtTerminal] 登录二维码推送中...
    llonebot  | [2025-05-11 10:33:17] [LoginAtTerminal] 登录二维码推送中...
    ```
3. 数据支持指定目录持久化吗？现在每次 `docker compose down && docker compose up -d`  后得重新扫码登录，这样断电啥的就得重新操作，没法丢那不管……
